import { useEffect, useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Loader from '../components/loader'
import Script from 'next/script'
import styles from '../styles/Home.module.css'

export default function Home() {
	const [muted, setMuted] = useState(true)
	const [loaded, setLoaded] = useState(false)
	const [waitingForLoad, setWaitingForLoad] = useState(false)
	const [playing, setPlaying] = useState(false)
	useEffect(() => {
		const audio = document.querySelector('audio')
		if (audio) {
			audio.addEventListener('playing', () => {
				console.log('loaded')
				setLoaded(true)
				if (!muted) setPlaying(true)
				if (waitingForLoad) setWaitingForLoad(false)
			})
		}
	}, [muted, waitingForLoad])
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Script
				strategy='beforeInteractive'
				src='https://code.jquery.com/jquery-1.11.3.min.js'
			/>
			<Script
				strategy='beforeInteractive'
				src='https://public.radio.co/playerapi/jquery.radiocoplayer.min.js'
			/>

			<main className={styles.main}>
				<h1
					style={{
						fontWeight: 'normal',
						textTransform: 'uppercase',
						letterSpacing: '.2em',
					}}
				>
					Ghost Radio
				</h1>
				<Image
					src='/ghost.png'
					alt='Ghost of Frank Dukes ghost icon'
					width={350 / 2}
					height={350 / 2}
				></Image>
				<div style={{ marginTop: '1.3em', height: 50, display: 'flex' }}>
					{waitingForLoad ? (
						<Loader></Loader>
					) : (
						<button
							style={{
								background: 'none',
								color: 'black',
								padding: '.4em .8em',
								fontSize: '1em',
								fontFamily: 'sans-serif',
								fontStyle: 'italic',
								letterSpacing: '.03em',
								border: 'none',
							}}
							className={`button button--play ${!muted && 'button--active'}`}
							onClick={(e) => {
								const audio = document.querySelector('#radioco-radioplayer')
								const muteState = !muted
								audio.muted = muteState
								setMuted(muteState)
								if (!muteState && !loaded) setWaitingForLoad(true)
							}}
						>
							{/* {muted ? 'PLAY' : 'STOP'} */}
							<div className='button__shape button__shape--one'></div>
							<div className='button__shape button__shape--two'></div>
						</button>
					)}
				</div>
				<div
					style={{
						opacity: muted || waitingForLoad ? 0 : 1,
					}}
				>
					<div
						className='radioplayer'
						data-src='https://stream.radio.co/se553dac9b/listen'
						data-autoplay='true'
						data-playbutton='true'
						data-volumeslider='false'
						data-elapsedtime='false'
						data-nowplaying='false'
						data-showplayer='false'
						data-volume='0'
						data-showartwork='false'
					></div>
				</div>
			</main>
			<Script id='load-radio-player' strategy='lazyOnload'>
				{`
          $('.radioplayer').radiocoPlayer()
        `}
			</Script>

			<footer className={styles.footer}>
				<p>
					Audio from the{' '}
					<a href='https://ghostofnft.io'>Ghost of Frank Dukes NFT project</a>.
					&copy; 2022 Adam Feeney
				</p>
			</footer>
		</div>
	)
}
